version: "3.9"

services:
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    working_dir: /app
    # volumes:
    #   - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev", "--", "--host"]

  backend:
    build:
      context: ./socket
    ports:
      - "5700:5700"
    working_dir: /app
    volumes:
      - ./socket:/app
    command: ["uvicorn", "websocket:app", "--host", "0.0.0.0", "--port", "5700", "--reload"]
