-- EagleEye: public schema (custom tables only).
-- A new Supabase project already includes auth, storage, realtime, etc.
-- Apply via Dashboard → SQL → New query → paste, or: psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f db/eagleeye_public_schema.sql

SET client_encoding = 'UTF8';

-- Name: EagleEye_traffic_data; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EagleEye_traffic_data" (
    id bigint NOT NULL,
    "time" timestamp with time zone DEFAULT now() NOT NULL,
    objects json,
    total_items bigint,
    fps double precision,
    index text
);


ALTER TABLE public."EagleEye_traffic_data" OWNER TO postgres;

--
-- Name: EagleEye traffic data_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."EagleEye_traffic_data" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EagleEye traffic data_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: blacklisted_jti; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.blacklisted_jti (
    id bigint NOT NULL,
    username text NOT NULL,
    jti text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    blacklist boolean,
    expire_at timestamp with time zone
);


ALTER TABLE public.blacklisted_jti OWNER TO postgres;

--
-- Name: blacklisted_jti_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.blacklisted_jti ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.blacklisted_jti_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    username text NOT NULL,
    token text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    disabled boolean NOT NULL,
    expire_at timestamp with time zone
);


ALTER TABLE public.refresh_tokens OWNER TO postgres;

--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_info; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_info (
    id bigint NOT NULL,
    username text NOT NULL,
    fps smallint DEFAULT '2'::smallint NOT NULL,
    "inputSource" text,
    "rtspLinks" json DEFAULT '{}'::json NOT NULL,
    "enableAnnotationsRef" boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT (now() AT TIME ZONE 'utc'::text) NOT NULL,
    email text
);


ALTER TABLE public.user_info OWNER TO postgres;

--
-- Name: user_info_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_info ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_info_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_login; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_login (
    username text NOT NULL,
    password text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.users_login OWNER TO postgres;

-- Name: EagleEye_traffic_data EagleEye traffic data_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EagleEye_traffic_data"
    ADD CONSTRAINT "EagleEye traffic data_id_key" UNIQUE (id);


--
-- Name: EagleEye_traffic_data EagleEye traffic data_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EagleEye_traffic_data"
    ADD CONSTRAINT "EagleEye traffic data_pkey" PRIMARY KEY (id);


--
-- Name: blacklisted_jti blacklisted_jti_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blacklisted_jti
    ADD CONSTRAINT blacklisted_jti_pkey PRIMARY KEY (id, username);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id, username);


--
-- Name: user_info user_info_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_info
    ADD CONSTRAINT user_info_id_key UNIQUE (id);


--
-- Name: user_info user_info_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_info
    ADD CONSTRAINT user_info_pkey PRIMARY KEY (username);


--
-- Name: users_login users_login_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_login
    ADD CONSTRAINT users_login_pkey PRIMARY KEY (username);

-- Name: blacklisted_jti blacklisted_jti_username_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.blacklisted_jti
    ADD CONSTRAINT blacklisted_jti_username_fkey FOREIGN KEY (username) REFERENCES public.users_login(username) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: refresh_tokens refresh_tokens_username_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_username_fkey FOREIGN KEY (username) REFERENCES public.users_login(username) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: user_info user_info_username_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_info
    ADD CONSTRAINT user_info_username_fkey FOREIGN KEY (username) REFERENCES public.users_login(username) ON UPDATE CASCADE ON DELETE CASCADE;


-- Name: TABLE "EagleEye_traffic_data"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public."EagleEye_traffic_data" TO anon;
GRANT ALL ON TABLE public."EagleEye_traffic_data" TO authenticated;
GRANT ALL ON TABLE public."EagleEye_traffic_data" TO service_role;


--
-- Name: SEQUENCE "EagleEye traffic data_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public."EagleEye traffic data_id_seq" TO anon;
GRANT ALL ON SEQUENCE public."EagleEye traffic data_id_seq" TO authenticated;
GRANT ALL ON SEQUENCE public."EagleEye traffic data_id_seq" TO service_role;


--
-- Name: TABLE blacklisted_jti; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.blacklisted_jti TO anon;
GRANT ALL ON TABLE public.blacklisted_jti TO authenticated;
GRANT ALL ON TABLE public.blacklisted_jti TO service_role;


--
-- Name: SEQUENCE blacklisted_jti_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.blacklisted_jti_id_seq TO anon;
GRANT ALL ON SEQUENCE public.blacklisted_jti_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.blacklisted_jti_id_seq TO service_role;


--
-- Name: TABLE refresh_tokens; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.refresh_tokens TO anon;
GRANT ALL ON TABLE public.refresh_tokens TO authenticated;
GRANT ALL ON TABLE public.refresh_tokens TO service_role;


--
-- Name: SEQUENCE refresh_tokens_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.refresh_tokens_id_seq TO anon;
GRANT ALL ON SEQUENCE public.refresh_tokens_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.refresh_tokens_id_seq TO service_role;


--
-- Name: TABLE user_info; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.user_info TO anon;
GRANT ALL ON TABLE public.user_info TO authenticated;
GRANT ALL ON TABLE public.user_info TO service_role;


--
-- Name: SEQUENCE user_info_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.user_info_id_seq TO anon;
GRANT ALL ON SEQUENCE public.user_info_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.user_info_id_seq TO service_role;


--
-- Name: TABLE users_login; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.users_login TO anon;
GRANT ALL ON TABLE public.users_login TO authenticated;
GRANT ALL ON TABLE public.users_login TO service_role;
